// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: SequentialCommandGroup.

package robot.commands;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import robot.subsystems.drivetrainSubSys;
import robot.subsystems.payloadSubSys;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class autoRedSingleCmdGrp extends SequentialCommandGroup {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    public autoRedSingleCmdGrp(drivetrainSubSys drivetrainSubSys, payloadSubSys payloadSubSys){

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    addCommands(
        // Add Commands here:
        // Also add parallel commands using the
        //
        // addCommands(
        //      new command1(argsN, subsystem),
        //      parallel(
        //          new command2(argsN, subsystem),
        //          new command3(argsN, subsystem)
        //      )    
        //  );

        /// SINGLE RED
        /*
        parallel(
            new intakeExtendCmd(payloadSubSys),
            new driveCmd(-44, -0.5, 0, "NEW_HEADING", 5, true, drivetrainSubSys)
        ),
        new delayCmd(2.0),
        new intakeRetractOnCmd(payloadSubSys),
        new intakeRetractOffCmd(true, payloadSubSys),

        new driveCmd(44, 0.5, 0, "NEW_HEADING", 5, true, drivetrainSubSys),
        new driveSwingTurnCmd(0.25, -0.25, 30, -25, "DIST", true, 5, drivetrainSubSys),

        new shooterFireOnCmd(true, payloadSubSys)
        */
        new resetGyroCmd(drivetrainSubSys),

        new intakeExtendCmd(payloadSubSys),
        
        new delayCmd(0.75),
        // driveSwingTurnCmd(speed, rotation, dist, hdg, mode, brakeFlag, timeOut, subsystem)
        new driveSwingTurnCmd(-0.3, -0.4, -15.0, 0, "DIST", false, 3, drivetrainSubSys),
        // driveCmd(dist, pwr, hdg, mode, timeOut, brakeFlag, subsystem)
        new driveCmd(-36, -0.4, 0, "CURRENT_HEADING", 8, true, drivetrainSubSys),
        
        new intakeRetractOnCmd(payloadSubSys),
        new intakeRetractOffCmd(true, payloadSubSys),
        
        new driveCmd(60, 0.4, -25, "NEW_HEADING", 10, true, drivetrainSubSys),
        
        //  drivePointTurnCmd(rotation, hdg, brakeFlag, timeOut, subsystem)
        //new drivePointTurnCmd(-0.4, -15, true, 3, drivetrainSubSys),

        new shooterFireOnCmd(true, payloadSubSys),
        new delayCmd(2.0),
        new shooterFireOffCmd(payloadSubSys)

        
        );
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
